"use client";

import { useEffect, useState } from "react";
import PayPalCheckout from "@/components/PayPalCheckout";
import { CheckCircle, Lock, Printer, Settings, Layout, ChevronLeft, Menu } from "lucide-react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { Sidebar } from "@/components/layout/Sidebar";
import { Modal, ModalFooter } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { useKeyPress, useAnnounce } from "@/lib/hooks";

interface CalendarEvent {
    summary: string;
    startDate: string;
    endDate: string;
    description?: string;
}

export default function PreviewPage() {
    const [events, setEvents] = useState<CalendarEvent[]>([]);
    const [layout, setLayout] = useState<"list" | "grid">("list");
    const [paperSize, setPaperSize] = useState<"a4" | "a5">("a4");
    const [isPro, setIsPro] = useState(false);
    const [showCheckout, setShowCheckout] = useState(false);
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const announce = useAnnounce();

    // Load events and pro status
    useEffect(() => {
        const stored = localStorage.getItem("calEvents");
        if (stored) {
            setEvents(JSON.parse(stored));
        }
        const proStatus = localStorage.getItem("isPro");
        if (proStatus === "true") setIsPro(true);
    }, []);

    // Keyboard shortcuts
    useKeyPress('p', () => handlePrint(), { ctrl: true });
    useKeyPress('l', () => {
        setLayout(prev => prev === 'list' ? 'grid' : 'list');
        announce(`Layout changed to ${layout === 'list' ? 'grid' : 'list'} view`, 'polite');
    }, { ctrl: true });

    const handlePrint = () => {
        announce('Opening print dialog', 'polite');
        window.print();
    };

    const handleProSuccess = (details: any) => {
        setIsPro(true);
        setShowCheckout(false);
        localStorage.setItem("isPro", "true");
        announce('Payment successful! Premium features unlocked', 'polite');
    };

    const handleLayoutChange = (newLayout: "list" | "grid") => {
        if (newLayout === 'grid' && !isPro) {
            setShowCheckout(true);
            announce('Grid view requires premium upgrade', 'polite');
        } else {
            setLayout(newLayout);
            announce(`Switched to ${newLayout} view`, 'polite');
        }
    };

    return (
        <div className="min-h-screen bg-[var(--color-neutral-100)] flex flex-col lg:flex-row relative">
            {/* Checkout Modal */}
            <Modal
                open={showCheckout}
                onClose={() => setShowCheckout(false)}
                title="Upgrade to Premium"
                description="Unlock advanced layouts and customization options"
                size="md"
            >
                {/* Features List */}
                <div className="space-y-4 mb-8">
                    <div className="flex items-center gap-3">
                        <CheckCircle size={20} className="text-[var(--color-success-600)] flex-shrink-0" />
                        <span className="text-[var(--color-neutral-700)]">Grid & Monthly Calendar Layouts</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <CheckCircle size={20} className="text-[var(--color-success-600)] flex-shrink-0" />
                        <span className="text-[var(--color-neutral-700)]">Remove 'Generated by' Footer</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <CheckCircle size={20} className="text-[var(--color-success-600)] flex-shrink-0" />
                        <span className="text-[var(--color-neutral-700)]">Custom Fonts & Color Themes</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <CheckCircle size={20} className="text-[var(--color-success-600)] flex-shrink-0" />
                        <span className="text-[var(--color-neutral-700)]">Priority Support</span>
                    </div>
                </div>

                {/* Payment Section */}
                <div className="border-t border-[var(--color-neutral-200)] pt-6">
                    <p className="text-center text-[var(--color-neutral-600)] text-sm mb-4">
                        One-time payment • Lifetime access
                    </p>
                    <div className="text-center mb-6">
                        <span className="text-4xl font-bold text-[var(--color-neutral-900)]">$5</span>
                        <span className="text-[var(--color-neutral-600)] ml-2">USD</span>
                    </div>
                    <PayPalCheckout amount="5.00" onSuccess={handleProSuccess} />
                </div>
            </Modal>

            {/* Mobile Menu Button */}
            <button
                onClick={() => setSidebarOpen(true)}
                className={cn(
                    'lg:hidden fixed top-4 right-4 z-50',
                    'p-3 rounded-xl',
                    'bg-white shadow-lg',
                    'text-[var(--color-neutral-700)] hover:text-[var(--color-neutral-900)]',
                    'border border-[var(--color-neutral-200)]',
                    'transition-colors',
                    'print:hidden',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-500)]'
                )}
                aria-label="Open settings sidebar"
            >
                <Menu size={24} />
            </button>

            {/* Sidebar */}
            <Sidebar
                isOpen={sidebarOpen || true} // Always open on desktop
                onClose={() => setSidebarOpen(false)}
                position="right"
                className="print:hidden"
            >
                {/* Back Link */}
                <Link
                    href="/upload"
                    className={cn(
                        'flex items-center text-[var(--color-neutral-600)] hover:text-[var(--color-neutral-900)]',
                        'mb-6 text-sm transition-colors',
                        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-500)] rounded-md px-2 py-1'
                    )}
                >
                    <ChevronLeft size={16} className="mr-1" />
                    Back to Upload
                </Link>

                {/* Header */}
                <div className="mb-8">
                    <h1 className="text-2xl font-bold text-[var(--color-neutral-900)] mb-2">
                        Print Settings
                    </h1>
                    {isPro && (
                        <Badge variant="success" size="md">
                            PRO
                        </Badge>
                    )}
                </div>

                {/* Upgrade CTA */}
                {!isPro && (
                    <div className="mb-8 p-6 bg-gradient-to-br from-[var(--color-primary-600)] to-[var(--color-primary-700)] rounded-xl text-white shadow-md">
                        <h4 className="font-bold text-lg mb-2">Unlock Premium</h4>
                        <p className="text-[var(--color-primary-100)] text-sm mb-4">
                            Get advanced layouts, customization, and more.
                        </p>
                        <Button
                            variant="secondary"
                            size="md"
                            onClick={() => setShowCheckout(true)}
                            fullWidth
                        >
                            Upgrade for $5
                        </Button>
                    </div>
                )}

                {/* Settings */}
                <div className="space-y-8 flex-1">
                    {/* Layout Selection */}
                    <section>
                        <h3 className="text-sm font-semibold text-[var(--color-neutral-900)] uppercase tracking-wider mb-3 flex items-center gap-2">
                            <Layout size={16} /> Layout
                        </h3>
                        <div className="grid grid-cols-2 gap-3">
                            <button
                                onClick={() => handleLayoutChange("list")}
                                className={cn(
                                    'p-3 rounded-lg border text-left text-sm transition-all',
                                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-500)]',
                                    layout === "list"
                                        ? "border-[var(--color-primary-600)] bg-[var(--color-primary-50)] text-[var(--color-primary-700)] ring-2 ring-[var(--color-primary-600)]"
                                        : "border-[var(--color-neutral-300)] hover:border-[var(--color-neutral-400)] text-[var(--color-neutral-700)]"
                                )}
                                aria-pressed={layout === "list"}
                            >
                                <div className="font-medium mb-1">List View</div>
                                <div className="text-xs opacity-75">Chronological list</div>
                            </button>
                            <button
                                onClick={() => handleLayoutChange("grid")}
                                className={cn(
                                    'p-3 rounded-lg border text-left text-sm transition-all relative overflow-hidden',
                                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-500)]',
                                    layout === "grid"
                                        ? "border-[var(--color-primary-600)] bg-[var(--color-primary-50)] text-[var(--color-primary-700)] ring-2 ring-[var(--color-primary-600)]"
                                        : "border-[var(--color-neutral-300)] hover:border-[var(--color-neutral-400)] text-[var(--color-neutral-700)]"
                                )}
                                aria-pressed={layout === "grid"}
                                aria-label={!isPro ? "Grid view - Premium feature" : "Grid view"}
                            >
                                {!isPro && (
                                    <div className="absolute inset-0 bg-[var(--color-neutral-100)]/80 backdrop-blur-[1px] flex items-center justify-center">
                                        <Lock size={16} className="text-[var(--color-neutral-500)]" />
                                    </div>
                                )}
                                <div className="font-medium mb-1">Grid View</div>
                                <div className="text-xs opacity-75">Monthly calendar</div>
                            </button>
                        </div>
                    </section>

                    {/* Paper Size */}
                    <section>
                        <h3 className="text-sm font-semibold text-[var(--color-neutral-900)] uppercase tracking-wider mb-3 flex items-center gap-2">
                            <Settings size={16} /> Paper Size
                        </h3>
                        <select
                            value={paperSize}
                            onChange={(e) => setPaperSize(e.target.value as "a4" | "a5")}
                            className={cn(
                                'w-full p-3 rounded-lg border border-[var(--color-neutral-300)]',
                                'bg-white text-[var(--color-neutral-900)] text-sm',
                                'focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]',
                                'cursor-pointer'
                            )}
                            aria-label="Select paper size"
                        >
                            <option value="a4">A4 (210 × 297 mm)</option>
                            <option value="a5">A5 (148 × 210 mm)</option>
                        </select>
                    </section>
                </div>

                {/* Print Button */}
                <div className="pt-6 border-t border-[var(--color-neutral-200)] mt-8">
                    <Button
                        variant="primary"
                        size="lg"
                        onClick={handlePrint}
                        leftIcon={<Printer size={20} />}
                        fullWidth
                    >
                        Print Now
                    </Button>
                    <p className="text-center text-xs text-[var(--color-neutral-500)] mt-3">
                        Tip: Enable "Background Graphics" in print dialog
                    </p>
                    <p className="text-center text-xs text-[var(--color-neutral-500)] mt-1">
                        <kbd className="px-1 py-0.5 rounded bg-[var(--color-neutral-200)] font-mono">Ctrl+P</kbd> to print
                    </p>
                </div>
            </Sidebar>

            {/* Main Preview Area */}
            <main className="flex-1 p-4 sm:p-10 lg:pr-10 print:p-0 overflow-auto">
                {/* The Paper Component */}
                <div
                    className={cn(
                        'bg-white paper-shadow mx-auto p-[10mm] print:shadow-none print:p-0',
                        paperSize === "a4" ? "w-full max-w-[210mm] min-h-[297mm]" : "w-full max-w-[148mm] min-h-[210mm]",
                        'print:w-full print:max-w-full print:h-auto'
                    )}
                    role="article"
                    aria-label="Calendar preview"
                >
                    {/* Header */}
                    <header className="border-b-2 border-[var(--color-neutral-900)] pb-4 mb-8 flex justify-between items-end">
                        <div>
                            <h1 className="text-3xl sm:text-4xl font-extrabold text-[var(--color-neutral-900)] tracking-tight">
                                MY DIARY
                            </h1>
                            <p className="text-[var(--color-neutral-600)] mt-1 uppercase tracking-widest text-xs">
                                Generated by CalToPaper
                            </p>
                        </div>
                        <div className="text-right">
                            <p className="text-xl font-bold text-[var(--color-neutral-900)]">2026</p>
                        </div>
                    </header>

                    {/* Layout Content */}
                    {layout === "list" ? (
                        <div className="space-y-6">
                            {events.length === 0 ? (
                                <div className="text-center py-12 text-[var(--color-neutral-500)]">
                                    <p>No events to display</p>
                                    <Link
                                        href="/upload"
                                        className="text-[var(--color-primary-600)] hover:text-[var(--color-primary-700)] underline text-sm mt-2 inline-block"
                                    >
                                        Upload a calendar file
                                    </Link>
                                </div>
                            ) : (
                                events.map((event, idx) => (
                                    <div key={idx} className="flex gap-4">
                                        <div className="w-20 sm:w-24 pt-1 text-right flex-shrink-0">
                                            <span className="block text-xl font-bold text-[var(--color-neutral-900)] leading-none">
                                                {new Date(event.startDate).getDate()}
                                            </span>
                                            <span className="block text-xs font-semibold text-[var(--color-neutral-600)] uppercase mt-1">
                                                {new Date(event.startDate).toLocaleDateString('en-US', { month: 'short', weekday: 'short' })}
                                            </span>
                                        </div>
                                        <div className="flex-1 pt-1 pb-6 border-b border-[var(--color-neutral-200)] border-dashed">
                                            <h3 className="text-base sm:text-lg font-medium text-[var(--color-neutral-900)] mb-1">
                                                {event.summary}
                                            </h3>
                                            {event.description && (
                                                <p className="text-sm text-[var(--color-neutral-600)] line-clamp-2">
                                                    {event.description}
                                                </p>
                                            )}
                                            <div className="mt-2 text-xs font-medium text-[var(--color-primary-700)] bg-[var(--color-primary-50)] inline-block px-2 py-1 rounded">
                                                {new Date(event.startDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                            </div>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    ) : (
                        <div className="grid grid-cols-7 gap-2">
                            {/* Grid Calendar Header */}
                            {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => (
                                <div key={day} className="text-center font-bold text-xs uppercase text-[var(--color-neutral-500)] py-2">
                                    {day}
                                </div>
                            ))}
                            {/* Grid Calendar Days */}
                            {Array.from({ length: 35 }).map((_, i) => (
                                <div key={i} className="aspect-square border border-[var(--color-neutral-200)] p-1 relative rounded">
                                    <span className="text-xs text-[var(--color-neutral-500)] absolute top-1 left-1">{i + 1}</span>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </main>

            {/* Print Styles */}
            <style jsx global>{`
                @media print {
                    body { background: white; margin: 0; }
                    .print\\:hidden { display: none !important; }
                    .print\\:p-0 { padding: 0 !important; }
                    .print\\:w-full { width: 100% !important; }
                    .print\\:max-w-full { max-width: 100% !important; }
                    .print\\:h-auto { height: auto !important; }
                    .print\\:shadow-none { box-shadow: none !important; }
                    @page { margin: 0; size: auto; }
                }
            `}</style>
        </div>
    );
}
